-- MySQL Script generated by MySQL Workbench
-- Tue Feb 14 19:20:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema digitalB01
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `digitalB01` ;

-- -----------------------------------------------------
-- Schema digitalB01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `digitalB01` DEFAULT CHARACTER SET utf8 ;
USE `digitalB01` ;

-- -----------------------------------------------------
-- Table `digitalB01`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `digitalB01`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `urlImagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
